version: '3'
services:
  tesseract:
    build: .
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8889:8889
    volumes:
      - ./work:/home/work
    working_dir: /home/work
    command: jupyter lab --ip 0.0.0.0 --port 8889 --allow-root